HistSimulation: initialsimulation.c File Reference
initialsimulation.c File Reference
#include "initialsimulation.h"
Macros
#define MAX_SYS 200
#define EXP_FAR 0
#define EXP_NEAR 1
Functions
double min (double x, double y)
double square (double x)
double likelihood (double true_rate, double fit_rate, double sqr_sigma)
double chiDCNorm (int exp, int rule, int n_params, double *x, double *errors, void *user_data)
double chiDCSpectral (int exp, int rule, int n_params, double *x, double *errors, void *user_data)
double DoChiSquare (double x, void *dummy)
void gslError (const char *reason, const char *file, int line, int gsl_errno)
void ComputeSensitivityCurve ()
int main (int argc, char *argv[])
Variables
char MYFILE1 [] ="histsima.dat"
char MYFILE2 [] ="histsimb.dat"
char MYFILE3 [] ="histsim1.dat"
double theta12
double theta13
double theta23
double deltacp
double sdm
double ldm
glb_params true_values
glb_params test_values
glb_params input_errors
const gsl_root_fsolver_type * T
gsl_root_fsolver * s
gsl_function gsl_func
const double min_runtime = 1e-2
const double max_runtime = 1e4
const double chi2_goal = 2.7
const int tSteps = 30
const double logs22th13_precision = 0.005
double sys_errors [MAX_SYS]
double sys_startval [MAX_SYS]
double sigma_binbin = 0.0
Macro Definition Documentation
EXP_FAR
#define EXP_FAR 0
Definition at line 66 of file initialsimulation.c.
Referenced by chiDCNorm(), chiDCSpectral(), ComputeSensitivityCurve(), DoChiSquare(), and main().
EXP_NEAR
#define EXP_NEAR 1
Definition at line 67 of file initialsimulation.c.
Referenced by chiDCNorm(), chiDCSpectral(), ComputeSensitivityCurve(), and main().
MAX_SYS
#define MAX_SYS 200
Definition at line 61 of file initialsimulation.c.
Referenced by main().
Function Documentation
chiDCNorm()
double chiDCNorm (int exp, int rule, int n_params, double * x, double * errors, void * user_data)
Definition at line 114 of file initialsimulation.c.
References EXP_FAR, EXP_NEAR, likelihood(), square(), and sys_startval.
Referenced by main().
{
   int n_bins = glbGetNumberOfBins(EXP_FAR);
   double *true_rates_N = glbGetRuleRatePtr(EXP_NEAR, 0);
   double *true_rates_F = glbGetRuleRatePtr(EXP_FAR, 0);
   double signal_fit_rates_N[n_bins];
   double signal_fit_rates_F[n_bins];
   double signal_norm_N, signal_norm_F;
   int ew_low, ew_high;
   double emin, emax;
   double fit_rate;
   double chi2 = 0.0;
   int i;
   /* Request simulated energy interval and analysis energy window */
   glbGetEminEmax(exp, &emin, &emax);
   glbGetEnergyWindowBins(exp, rule, &ew_low, &ew_high);
   /* Apply energy calibration error */
   glbShiftEnergyScale(x[3], glbGetSignalFitRatePtr(EXP_FAR, 0),
                       signal_fit_rates_F, n_bins, emin, emax);
   glbShiftEnergyScale(x[4], glbGetSignalFitRatePtr(EXP_NEAR, 0),
                       signal_fit_rates_N, n_bins, emin, emax);
   /* Loop over all bins in energy window */
   signal_norm_F = 1.0 + x[0] + x[1];
   signal_norm_N = 1.0 + x[0] + x[2];
   for (i=ew_low; i <= ew_high; i++)
   {
     /* Statistical part of chi^2 for far detector
      * Normalization is affected by flux error x[0] and fiducial mass error x[1] */
     fit_rate  = signal_norm_F * signal_fit_rates_F[i];
     chi2 += likelihood(true_rates_F[i], fit_rate, true_rates_F[i]);
     /* Statistical part of chi^2 for near detector
      * Normalization is affected by flux error x[0] and fiducial mass error x[2] */
     fit_rate  = signal_norm_N * signal_fit_rates_N[i];
     chi2 += likelihood(true_rates_N[i], fit_rate, true_rates_N[i]);
   }
   /* Systematical part of chi^2 (= priors) */
   for (i=0; i < n_params; i++)
     chi2 += square(x[i] / errors[i]);
   /* Save the systematics parameters as starting values for the next step */
   for (i=0; i < n_params; i++)
     sys_startval[i] = x[i];
   return chi2;
 }
chiDCSpectral()
double chiDCSpectral (int exp, int rule, int n_params, double * x, double * errors, void * user_data)
Definition at line 178 of file initialsimulation.c.
References EXP_FAR, EXP_NEAR, likelihood(), sigma_binbin, square(), and sys_startval.
Referenced by main().
{
   int n_bins = glbGetNumberOfBins(EXP_FAR);
   double *true_rates_N = glbGetRuleRatePtr(EXP_NEAR, 0);
   double *true_rates_F = glbGetRuleRatePtr(EXP_FAR, 0);
   double signal_fit_rates_N[n_bins];
   double signal_fit_rates_F[n_bins];
   double signal_norm_N, signal_norm_F;
   int ew_low, ew_high;
   double emin, emax;
   double fit_rate;
   double chi2 = 0.0;
   int i;
   /* Request simulated energy interval and analysis energy window */
   glbGetEminEmax(exp, &emin, &emax);
   glbGetEnergyWindowBins(exp, rule, &ew_low, &ew_high);
   /* Apply energy calibration error */
   glbShiftEnergyScale(x[3], glbGetSignalFitRatePtr(EXP_FAR, 0),
                       signal_fit_rates_F, n_bins, emin, emax);
   glbShiftEnergyScale(x[4], glbGetSignalFitRatePtr(EXP_NEAR, 0),
                       signal_fit_rates_N, n_bins, emin, emax);
   /* Loop over all bins in energy window */
   signal_norm_F = 1.0 + x[0] + x[1];
   signal_norm_N = 1.0 + x[0] + x[2];
   for (i=ew_low; i <= ew_high; i++)
   {
     /* Statistical part of chi^2 for far detector
      * Normalization is affected by flux error x[0], fiducial mass error x[1],
      * spectral perturbations x[5+i], and bin-to-bin error sigma_binbin */
     fit_rate  = (signal_norm_F + x[5+i]) * signal_fit_rates_F[i];
     chi2 += likelihood( true_rates_F[i], fit_rate,
                     true_rates_F[i] * (1.0 + true_rates_F[i]*square(sigma_binbin)) );
     /* Statistical part of chi^2 for near detector
      * Normalization is affected by flux error x[0], fiducial mass error x[2],
      * spectral perturbations x[5+i], and bin-to-bin error sigma_binbin */
     fit_rate  = (signal_norm_N + x[5+i]) * signal_fit_rates_N[i];
     chi2 += likelihood( true_rates_N[i], fit_rate,
                     true_rates_N[i] * (1.0 + true_rates_N[i]*square(sigma_binbin)) );
   }
   /* Systematical part of chi^2 (= priors) */
   for (i=0; i < n_params; i++)
     chi2 += square(x[i] / errors[i]);
   /* Save the systematics parameters as starting values for the next step */
   for (i=0; i < n_params; i++)
     sys_startval[i] = x[i];
   return chi2;
 }
ComputeSensitivityCurve()
void ComputeSensitivityCurve ()
Definition at line 274 of file initialsimulation.c.
References AddToOutput2(), deltacp, EXP_FAR, EXP_NEAR, gsl_func, input_errors, ldm, logs22th13_precision, max_runtime, min(), min_runtime, s, sdm, test_values, theta12, theta13, theta23, true_values, tSteps, and quickplot::x.
Referenced by main().
{
   double t_factor = pow(max_runtime/min_runtime, 1.0/tSteps);
   double t;
   double x;               /* Current value of log[sin^2(2*th13)] */
   double x_lo, x_hi;      /* Bracketing interval for root finder */
   double x_sens[tSteps+1];/* Calculated sensitivities to log[sin^2(2*th13)] */
   int gsl_status;         /* GSL error code */
   int iter;               /* Iteration counter for root finder */
   const int max_iter=100; /* Maximum number of iterations allowed in root finder */
   int j;
   for (j=0; j <= tSteps; j++)      /* Initialize output vector */
     x_sens[j] = 1;                 /* As x is always <= 0 this signals "no value" */
   /* Loop over all data points in this dataset, using log stepping */
   for (j=0; j <= tSteps; j++)
   {
     /* Set running time */
     t = min_runtime * pow(t_factor,j);
     glbSetRunningTime(EXP_FAR, 0, t);
     glbSetRunningTime(EXP_NEAR, 0, t);
     /* Calculate "true" event rates */
     glbDefineParams(true_values,theta12,theta13,theta23,deltacp,sdm,ldm);
     glbSetDensityParams(true_values,1.0,GLB_ALL);
     glbDefineParams(test_values,theta12,theta13,theta23,deltacp,sdm,ldm);
     glbSetDensityParams(test_values,1.0,GLB_ALL);
     glbDefineParams(input_errors, 0.1*theta12, 0, 0.15*theta23, 0, 0.05*sdm, 0.05*ldm);
     glbSetDensityParams(input_errors, 0.05, GLB_ALL);
     glbSetOscillationParameters(true_values);
     glbSetInputErrors(input_errors);
     glbSetRates();
     /* Determine sensitivity to sin^2(2*th13) by  using the GSL Brent-Dekker
      * algorithm to find the th13, for which chi^2 = 2.7 (90%) */
     x_lo = -3.0;
     x_hi = -0.1;
     iter = 0;
     /* Start root finder. The initial search interval is guessed based on the
      * results from a neighboring grid point */
     double deviation=0.1;
     do {
       if (j > 0) {
         x_lo = x_sens[j-1] - deviation;
         x_hi = min(x_sens[j-1] + deviation, -0.001);
       }
       gsl_status = gsl_root_fsolver_set(s, &gsl_func, x_lo, x_hi);
       deviation *= 2;
     } while (gsl_status != GSL_SUCCESS);
     /* Iterate root finder */
     do {
       gsl_status = gsl_root_fsolver_iterate(s);
       x          = gsl_root_fsolver_root(s);
       x_lo       = gsl_root_fsolver_x_lower(s);
       x_hi       = gsl_root_fsolver_x_upper(s);
       gsl_status = gsl_root_test_interval (x_lo, x_hi, logs22th13_precision, 0);
     } while (gsl_status == GSL_CONTINUE && iter < max_iter);
     /* Save results */
     x_sens[j] = x;
     AddToOutput2(t, x);
   // Setting up output
   int max_channel_id = 17;
   char buf[60];
   char str[60];
   for(int i=0; i<max_channel_id+1;i++){
     sprintf(buf,"%dtime2histsim_channel%d.dat",j,i);
     strcpy(str,buf);
     FILE* f_out = fopen(str,"w");
     // double hist_time = 100000;
     // glbSetRunningTime(EXP_NEAR,0,hist_time);
     //printf("Running time is; %f",glbGetRunningTime(1,0));
     glbShowChannelRates(f_out,EXP_NEAR,i,GLB_PRE,GLB_WO_EFF,GLB_WO_BG);
   fclose(f_out);
   }
   }
 }
DoChiSquare()
double DoChiSquare (double x, void * dummy)
Definition at line 239 of file initialsimulation.c.
References chi2_goal, EXP_FAR, sys_startval, and test_values.
Referenced by main().
{
   double thetheta13, chi2;
   /* Set vector of test values */
   thetheta13 = asin(sqrt(pow(10,x)))/2;
   glbSetOscParams(test_values, thetheta13, GLB_THETA_13);
   glbSetOscParams(test_values, 200.0/2 * (x+4)*M_PI/180, GLB_DELTA_CP);
   /* Set starting values for systematics minimiyer to the coordinates of
    * minimum in the last iteration. This accelerates the minimization and
    * prevents convergence problems. */
   glbSetSysStartingValuesList(EXP_FAR, 0, GLB_ON, sys_startval);
   /* Compute Chi^2 for all loaded experiments and all rules
    * Correlations are unimportant in reactor experiments, so glbChiSys is sufficient */
   chi2 = glbChiSys(test_values, GLB_ALL, GLB_ALL);
   return chi2 - chi2_goal;
 }
gslError()
void gslError (const char * reason, const char * file, int line, int gsl_errno)
Definition at line 261 of file initialsimulation.c.
Referenced by main().
{
   static int n_errors=0;
   printf("GSL Error in file %s:%d : %s\n", file, line, gsl_strerror(gsl_errno));
   if (++n_errors > 1000)
   {
     printf("Too many GSL errors. Program aborted.\n");
     abort();
   }
 }
likelihood()
double likelihood (double true_rate, double fit_rate, double sqr_sigma) inline
Definition at line 91 of file initialsimulation.c.
References square().
Referenced by chiDCNorm(), and chiDCSpectral().
 {
   if (sqr_sigma > 0)
     return square(true_rate - fit_rate) / sqr_sigma;
   else
     return 0.0;
 }
main()
int main (int argc, char * argv[])
Definition at line 375 of file initialsimulation.c.
References chiDCNorm(), chiDCSpectral(), ComputeSensitivityCurve(), deltacp, DoChiSquare(), EXP_FAR, EXP_NEAR, gsl_func, gslError(), InitOutput(), input_errors, ldm, MAX_SYS, MYFILE1, MYFILE2, s, sdm, sys_startval, T, test_values, theta12, theta13, theta23, and true_values.
 {
   double *old_sys_errors = NULL;      /* Temp. pointer to systematical error array */
   int sys_dim;                        /* Abbrv. for number of systematical errors */
   int n_bins=86;                      /* Number of bins */
   int i;
   /* Initialization */
   for (i=0; i < MAX_SYS; i++)
     sys_startval[i] = 0.0;
   /* Set standard oscillation parameters (cf. hep-ph/0405172v5) */
   theta12 = asin(sqrt(0.3));
   theta13 = 0.0;
   theta23 = M_PI/4;
   deltacp = M_PI/2;
   sdm = 7.9e-5;
   ldm = 2.6e-3;
   glbInit(argv[0]);                    /* Initialize GLoBES and define chi^2 functions */
   glbDefineChiFunction(&chiDCNorm,     5,        "chiDCNorm",     NULL);
   glbDefineChiFunction(&chiDCSpectral, 5+n_bins, "chiDCSpectral", NULL);
   gsl_set_error_handler(&gslError);    /* Initialize GSL root finder */
   gsl_func.function = &DoChiSquare;
   gsl_func.params   = NULL;
   T = gsl_root_fsolver_brent;
   s = gsl_root_fsolver_alloc(T);
   /* Load 2 experiments: DC far (#0) and near (#1) detectors */
   glbClearExperimentList();
   glbInitExperiment("CHIPS-GLB/glb-CHIPS10-7mrad-ME-FAR.glb", &glb_experiment_list[0], &glb_num_of_exps);
   glbInitExperiment("CHIPS-GLB/glb-CHIPS10-7mrad-ME-NEAR.glb", &glb_experiment_list[0], &glb_num_of_exps);
   if (glbGetNumberOfBins(EXP_FAR) != n_bins || glbGetNumberOfBins(EXP_NEAR) != n_bins)
   {
     printf("ERROR: Number of bins changed in AEDL file, but not in C code (or vice-versa).\n");
     printf("nbins %i",n_bins);
     printf("far bins %i",glbGetNumberOfBins(EXP_FAR));
     printf("near bins %i",glbGetNumberOfBins(EXP_NEAR));
     return -1;
   }
   else
     n_bins = glbGetNumberOfBins(EXP_FAR);
   /* Initialize parameter vectors */
   true_values  = glbAllocParams();
   test_values  = glbAllocParams();
   input_errors = glbAllocParams();
   glbDefineParams(true_values,theta12,theta13,theta23,deltacp,sdm,ldm);
   glbSetDensityParams(true_values,1.0,GLB_ALL);
   glbDefineParams(test_values,theta12,theta13,theta23,deltacp,sdm,ldm);
   glbSetDensityParams(test_values,1.0,GLB_ALL);
   glbDefineParams(input_errors, 0.1*theta12, 0, 0.15*theta23, 0, 0.05*sdm, 0.05*ldm);
   glbSetDensityParams(input_errors, 0.05, GLB_ALL);
   glbSetOscillationParameters(true_values);
   glbSetInputErrors(input_errors);
   /* Calculate sensitivity curve without systematics */
   InitOutput(MYFILE1,"Format: Running time   Log(10,s22th13) sens. \n");
   glbSwitchSystematics(GLB_ALL, GLB_ALL, GLB_OFF);
   ComputeSensitivityCurve();
   glbSwitchSystematics(GLB_ALL, GLB_ALL, GLB_ON);
   /* Calculate sensitivity curve with normalization and energy calibration errors,
    * as defined in the AEDL files */
   InitOutput(MYFILE2,"Format: Running time   Log(10,s22th13) sens. \n");
   ComputeSensitivityCurve();
   printf("Number of channels: %d",glbGetNumberOfChannels(EXP_NEAR));
   for(int js = 0; js<=18;js++){
   printf("Channel: %s",glbValueToName(EXP_NEAR,"channel",js));
   }
   /* Clean up */
   glbFreeParams(true_values);
   glbFreeParams(test_values);
   glbFreeParams(input_errors);
   gsl_root_fsolver_free(s);
   return 0;
 }
min()
double min (double x, double y) inline
Definition at line 75 of file initialsimulation.c.
References quickplot::x, and quickplot::y.
Referenced by ComputeSensitivityCurve().
 {
   if (x < y)
     return x;
   else
     return y;
 }
square()
double square (double x) inline
Definition at line 84 of file initialsimulation.c.
References quickplot::x.
Referenced by chiDCNorm(), chiDCSpectral(), and likelihood().
 {
   return x*x;
 }
Variable Documentation
chi2_goal
const double chi2_goal = 2.7
Definition at line 57 of file initialsimulation.c.
Referenced by DoChiSquare().
deltacp
double deltacp
Definition at line 42 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
gsl_func
gsl_function gsl_func
Definition at line 52 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
input_errors
glb_params input_errors
Definition at line 47 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
ldm
double ldm
Definition at line 42 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
logs22th13_precision
const double logs22th13_precision = 0.005
Definition at line 59 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve().
max_runtime
const double max_runtime = 1e4
Definition at line 56 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve().
min_runtime
const double min_runtime = 1e-2
Definition at line 55 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve().
MYFILE1
char MYFILE1[] ="histsima.dat"
Definition at line 34 of file initialsimulation.c.
Referenced by main().
MYFILE2
char MYFILE2[] ="histsimb.dat"
Definition at line 35 of file initialsimulation.c.
Referenced by main().
MYFILE3
char MYFILE3[] ="histsim1.dat"
Definition at line 36 of file initialsimulation.c.
s
gsl_root_fsolver* s
Definition at line 51 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
sdm
double sdm
Definition at line 42 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
sigma_binbin
double sigma_binbin = 0.0
Definition at line 64 of file initialsimulation.c.
Referenced by chiDCSpectral().
sys_errors
double sys_errors[MAX_SYS]
Definition at line 62 of file initialsimulation.c.
sys_startval
double sys_startval[MAX_SYS]
Definition at line 63 of file initialsimulation.c.
Referenced by chiDCNorm(), chiDCSpectral(), DoChiSquare(), and main().
T
const gsl_root_fsolver_type* T
Definition at line 50 of file initialsimulation.c.
Referenced by main().
test_values
glb_params test_values
Definition at line 46 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), DoChiSquare(), and main().
theta12
double theta12
Definition at line 42 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
theta13
double theta13
Definition at line 42 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
theta23
double theta23
Definition at line 42 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
true_values
glb_params true_values
Definition at line 45 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve(), and main().
tSteps
const int tSteps = 30
Definition at line 58 of file initialsimulation.c.
Referenced by ComputeSensitivityCurve().